baseURL = 'https://idiot-alex.github.io/'
languageCode = 'zh-cn'
title = 'Hotstrip Site'
theme = 'paper'

# paper params
[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  # twitter = 'YOUR_TWITTER_ID'               # twitter.com/YOUR_TWITTER_ID
  # instagram = 'YOUR_INSTAGRAM_ID'           # instagram.com/YOUR_INSTAGRAM_ID
  # linkedin = 'YOUR_LINKEDIN_ID'             # linkedin.com/in/YOUR_LINKEDIN_ID
  # mastodon = 'YOUR_MASTODON_LINK'           # e.g. 'https://mastodon.instance/@xxx'
  github = 'github.com/Idiot-Alex'                 # github.com/YOUR_GITHUB_ID
  rss = true                                # show rss icon

  # home page profile
  avatar = 'https://avatars.githubusercontent.com/u/16541166?v=4'                 # gravatar email or image url
  name = 'Hotstrip'
  bio = '现技术人，终身学习者。会点儿 Java、Python，喜欢 Go'